FROM ubuntu:24.04 as rpi_image_build
ARG DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && apt install -y \
    wget \
    git \
    xz-utils \
    qemu-utils \
    parted \
    e2fsprogs \
    libguestfs-tools \
    guestfish \
    openssl \
    libssl-dev \
    linux-image-generic
WORKDIR /rasp
COPY src/image_build.sh /rasp
RUN chmod +x /rasp/image_build.sh
CMD ["/rasp/image_build.sh"]